### ISSUE TITLE
阿里云上脚本还是27.0

### ISSUE THREAD

**Issue by LuckyMango** [MvsCode/frp-onekey#13]
使用默认的github网速太慢总是下不下来，使用阿里云下载版本却是27.0。请问一下有没有更好的解决方案。万分感谢~

**Comment by MvsCode** [comment]
已同步

**Comment by LuckyMango** [comment]
> 已同步
万分感谢，刚才用阿里云ECS Ping了一下github完全Ping不同。谢谢同步到阿里云仓库

**Comment by MvsCode** [comment]
Have Done
