### ISSUE TITLE
为啥我启动不起来，一直是failed

### ISSUE THREAD

**Issue by ZhaiCanZC** [MvsCode/frp-onekey#7]
查看log文件，显示只运行到tcp和kcp绑定端口(我设置的是7000)

**Comment by MvsCode** [comment]
> 查看log文件，显示只运行到tcp和kcp绑定端口(我设置的是7000)

去防火墙看看端口有没有放行

**Comment by ZhaiCanZC** [comment]
我发现原来是我的80端口被占用了
