### ISSUE TITLE
国内服务器,使用阿里云安装,提示download /etc/init.d/frps... failed

### ISSUE THREAD

**Issue by fishheadhead** [MvsCode/frp-onekey#8]
centos6.5

**Comment by MvsCode** [comment]
安装时候，可以选择1.aliyun

**Comment by fishheadhead** [comment]
> 安装时候，可以选择1.aliyun

是的,我用阿里云安装的,因为我的服务器无法访问github

**Comment by MvsCode** [comment]
那就不可能了，我是把文件放在阿里云了，或者你直接用aliyun的脚本
wget https://code.aliyun.com/MvsCode/frp-onekey/raw/master/install-frps.sh -O ./install-frps.sh
chmod 700 ./install-frps.sh
./install-frps.sh install

**Comment by fishheadhead** [comment]
> 安装时候，可以选择1.aliyun



> 那就不可能了，我是把文件放在阿里云了，或者你直接用aliyun的脚本
> wget https://code.aliyun.com/MvsCode/frp-onekey/raw/master/install-frps.sh -O ./install-frps.sh
> chmod 700 ./install-frps.sh
> ./install-frps.sh install

好的,换成这个地址安装成功了.非常感谢
